ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "igdbRating" INTEGER;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "jugadores" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "requiereInternet" BOOLEAN;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "metaEnriquecida" BOOLEAN NOT NULL DEFAULT false;
