-- Santuario: caché de identidad visual, tiempos, preservación, crítica y multimedia
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "editor" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "hltbMain" DOUBLE PRECISION;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "hltbCompletionist" DOUBLE PRECISION;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "manualUrl" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "archiveIdentifier" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "openCriticScore" INTEGER;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "openCriticRecommend" INTEGER;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "openCriticTier" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "trailerYoutubeId" TEXT;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "screenshotsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "specsJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "santuarioEnriquecido" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Juego" ADD COLUMN IF NOT EXISTS "enriquecidoEn" TIMESTAMP(3);
